### ISSUE TITLE
Crash on S5

### ISSUE THREAD

**Issue by BenAlderfer** [BenAlderfer/RIT-Dining-Planner-Android#20]
Crash reported from an S5. Error occurred while highlighting and copying the current balance. Crash does not occur on other devices I tested.

java.lang.UnsupportedOperationException
in android.content.res.TypedArray.getColor

android.view.InflateException: Binary XML file line #27: Binary XML file line #27: Error inflating class TextView
	at android.view.LayoutInflater.inflate(LayoutInflater.java:551)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:429)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:380)
	at android.widget.Toast.makeText(Toast.java:471)
	at android.widget.Toast.makeText(Toast.java:531)
	at android.sec.clipboard.ClipboardExManager$1.handleMessage(ClipboardExManager.java:1263)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7224)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by: android.view.InflateException: Binary XML file line #27: Error inflating class TextView
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:847)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:527)
	... 11 more
Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 24: TypedValue{t=0x1d/d=0xff000000 a=3 r=0x7f0e000b}
	at android.content.res.TypedArray.getColor(TypedArray.java:449)
	at android.widget.TextView.<init>(TextView.java:1018)
	at android.widget.TextView.<init>(TextView.java:941)
	at android.support.v7.widget.ap.<init>(SourceFile:59)
	at android.support.v7.widget.ap.<init>(SourceFile:55)
	at android.support.v7.a.w.a(SourceFile:15103)
	at android.support.v4.i.p$a.onCreateView(SourceFile:44)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:758)
	... 15 more

**Comment by BenAlderfer** [comment]
This may help: http://stackoverflow.com/questions/8041537/how-to-reference-style-attributes-from-a-drawable/13471695#13471695

**Comment by BenAlderfer** [comment]
That link did not help. That issue was non-existent.
